language: node_js

node_js:
  - 8.9.0

cache:
  directories:
    - node_modules
    - cypress
    - codecov
    - /home/travis/.cache/Cypress

install:
  - npm install
  - npm install -g codecov
  - npm install -g cypress

script:
  - npm run test && codecov
  - npm run cypress:ci
